{"uuid": "a2f85f30-50b7-42d8-8df9-045e56fc53b7", "children": ["bc9499f8-c75a-408e-bfe8-059fe1c0b514"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chrome' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 180, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 870, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 739, in call_fixture_func\n    res = next(it)\n  File \"C:\\Python36-32\\lib\\site-packages\\pytest_selenium\\pytest_selenium.py\", line 174, in driver\n    driver = driver_class(**driver_kwargs)\n  File \"C:\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1543074517201, "stop": 1543074517203}], "start": 1543074517201, "stop": 1543074517899}